### PR TITLE
Add java format checking

### LINKED ISSUE #7: Add Java checkstyle checking for MaruSettings
Although we can't build MaruSettings with gradle now, we can use checkstyle script to check Java code style that doesn't need full building, and add it to GitHub actions to check later commits. We can use [google-java-format](https://github.com/google/google-java-format) with [AOSP codestyle](https://github.com/google/google-java-format/blob/5104d0b27888f3bfab7113f5606374cda5632102/scripts/google-java-format-diff.py#L56).

### PR DESCRIPTION
**Pull request by utzcoz**
Fix https://github.com/maruos/vendor_maruos_packages_apps_MaruSettings/issues/7

### CODE REVIEW

**Comment by utzcoz** [comment]
I tested building only locally. Looks like it doesn't run if there is no other github workflow. What about merging it directly and checking its function with later commit @pdsouza ?

**Review by pdsouza — APPROVED** [review]
LGTM

**Comment by pdsouza** [comment]
> I tested building only locally. Looks like it doesn't run if there is no other github workflow. What about merging it directly and checking its function with later commit @pdsouza ?

Sounds good. Let's try it.

**Comment by utzcoz** [comment]
@pdsouza , the merged checking result is here: https://github.com/maruos/vendor_maruos_packages_apps_MaruSettings/runs/3224452742?check_suite_focus=true

**Pull request merged**
